#!/usr/bin/env bash

if [[ -z "$USERNAME" ]]; then
  echo "Missing USERNAME!"
  exit 1
fi

if [[ -z "${HOST_PUBKEY[@]}" ]]; then
  echo "Missing HOST_PUBKEY!"
  exit 1
fi

PASSWORD="${PASSWORD:-"p@ssw0rd"}"
SSH_PORT="${SSH_PORT:-"22"}"
SSH_CONFIG_PATH="${SSH_CONFIG_PATH:-"/etc/ssh/sshd_config"}"

echo "Creating user "$USERNAME"..."

useradd -g sudo -s "$(which bash)" -m "$USERNAME"

echo "Setting "$USERNAME"'s password to "$PASSWORD"..."

echo ""$USERNAME":"$PASSWORD"" | chpasswd

echo "Backing up "$SSH_CONFIG_PATH"..."

mv "$SSH_CONFIG_PATH" "$SSH_CONFIG_PATH".bak

echo "Writing config to "$SSH_CONFIG_PATH"..."

echo "Port "$SSH_PORT"
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
PermitRootLogin no
X11Forwarding no
IgnoreRhosts yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
" > "$SSH_CONFIG_PATH"

echo "Writing pubkey to "$USERNAME"'s authorized keys..."

mkdir -p "/home/$USERNAME/.ssh"
echo "${HOST_PUBKEY[@]}" > "/home/$USERNAME/.ssh/authorized_keys"

echo "Restarting SSH service..."

service ssh restart
