#!/usr/bin/env bash

USERNAME="$1"
PASSWORD="$2"
HOST_PUBKEY="$3"
SSH_PORT="${4:-"22"}"
USER_SHELL="${5:-"$(which bash)"}"
SSH_CONFIG_PATH="${6:-"/etc/ssh/sshd_config"}"

if [[ -z "$USERNAME" ]]; then
  echo "Missing USERNAME!"
  exit 1
fi

if [[ -z "$PASSWORD" ]]; then
  echo "Missing PASSWORD!"
  exit 1
fi

if [[ -z "$HOST_PUBKEY" ]]; then
  echo "Missing HOST_PUBKEY!"
  exit 1
fi

useradd -g sudo -s "$(which bash)" -d /home/$USERNAME -p "$PASSWORD" $USERNAME

mv $SSH_CONFIG_PATH $SSH_CONFIG_PATH.bak

echo "Port $SSH_PORT
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
PermitRootLogin no
X11Forwarding no
IgnoreRhosts yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
" > $SSH_CONFIG_PATH

su -c 'mkdir -p $HOME/.ssh;
echo "$HOST_PUBKEY" > $HOME/.ssh/authorized_keys' $USERNAME

service ssh restart
